name: Markdown to PDF and HTML
run-name: ${{ github.actor }} generates a PDF
on: [push]
jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: BaileyJM02/markdown-to-pdf@v1.2.0
        with:
          input_dir: .
          output_dir: pdfs
          images_dir: images
          # for example <img src="./images/file-name.png">
          image_import: ./images
          # Default is true, can set to false to only get PDF files
          build_html: true
      - uses: actions/upload-artifact@v1
        with:
          name: docs
          path: pdfs
